# Generated by Django 4.1.1 on 2023-04-22 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_val', models.CharField(default='error', max_length=100)),
                ('right_val', models.CharField(default='error', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='media/default.png', upload_to='pics')),
                ('hash_val', models.CharField(default='default', max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='default', max_length=300)),
                ('image', models.CharField(default='default', max_length=300)),
                ('name', models.CharField(default='default', max_length=300)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('name', models.CharField(default='default', max_length=300)),
                ('email', models.CharField(default='default', max_length=300)),
                ('address', models.CharField(default='default', max_length=500)),
                ('city', models.CharField(default='default', max_length=300)),
                ('state', models.CharField(default='default', max_length=300)),
                ('zip', models.CharField(default='default', max_length=300)),
                ('namecard', models.CharField(default='default', max_length=300)),
                ('cardnumber', models.CharField(default='default', max_length=500)),
                ('month', models.CharField(default='default', max_length=300)),
                ('year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('uuid', models.CharField(default='default', max_length=300, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
